#!/usr/bin/with-contenv sh
# shellcheck shell=sh

echo "Running init-config"

# vhosts
# inspired from (= copy paste) from https://github.com/BytemarkHosting/docker-webdav
if [ -n "${SERVER_NAMES}" ]; then
    # Replace commas with spaces
    SERVER_ALIAS="$(printf '%s\n' "$SERVER_NAMES" | tr ',' ' ')"
    sed -i "s/localhost/$SERVER_ALIAS/g" /etc/nginx/nginx.conf
fi

# Add password hash, unless /etc/nginx/htpasswd already exists (bind mounted).
if [ ! -e "/etc/nginx/htpasswd" ]; then
  touch "/etc/nginx/htpasswd"
  if [ -n "${WEBDAV_PASSWORD_FILE}" ]; then
    if [ ! -f "$WEBDAV_PASSWORD_FILE" ]; then
      echo "Error: Password file does not exist at $WEBDAV_PASSWORD_FILE" >&2
      exit 1
    fi
    WEBDAV_PASSWORD="$(cat "$WEBDAV_PASSWORD_FILE")"
  fi

  if [ -n "${WEBDAV_USERNAME}" ] && [ -n "${WEBDAV_PASSWORD}" ]; then
    htpasswd -bc /etc/nginx/htpasswd "$WEBDAV_USERNAME" "$WEBDAV_PASSWORD"
    # root /data/$remote_user;
  else
    # no auth
    sed -i 's%auth_basic "Restricted";% %g' /etc/nginx/nginx.conf
    sed -i 's%auth_basic_user_file htpasswd;% %g' /etc/nginx/nginx.conf
  fi
fi

# timeouts
if [ -n "${TIMEOUTS_S}" ]; then
    # Replace commas with spaces
    sed -i "s/3600/$TIMEOUTS_S/g" /etc/nginx/nginx.conf
fi

# max upload
if [ -n "${CLIENT_MAX_BODY_SIZE}" ]; then
    # Replace commas with spaces
    sed -i "s/10G/$CLIENT_MAX_BODY_SIZE/g" /etc/nginx/nginx.conf
fi

# suppress Finder metadata 
if [ -n "${ALLOW_FINDER_METADATA}" ]; then
  # This is executed when ALLOW_FINDER_METADATA is NOT defined 
  # Suppress metadata files for macOS Finder
  #sed -i '/set $checkPropfind "";/a \    include conf.d/findermetadata.conf;' /etc/nginx/nginx.conf
  echo "Allow Finder metadata (not a default action)"
  sed -i 's/^[[:space:]]*include conf\.d\/findermetadata\.conf;/#&/' /etc/nginx/nginx.conf
fi
