#!/usr/bin/with-contenv sh

mkdir -p /config/nginx
mkdir -p /etc/nginx/conf.d

if [ ! -f /config/nginx/http.conf ]; then
    echo "Creating empty /config/nginx/http.conf"
    touch /config/nginx/http.conf
fi

if [ ! -f /config/nginx/server.conf ]; then
    echo "Creating empty /config/nginx/server.conf"
    touch /config/nginx/server.conf
fi

if [ ! -f /config/nginx/location.conf ]; then
    echo "Creating empty /config/nginx/location.conf"
    touch /config/nginx/location.conf
fi

if [ ! -L /etc/nginx/conf.d/http.conf ]; then
    echo "Linking /config/nginx/http.conf to /etc/nginx/conf.d/"
    ln -s /config/nginx/http.conf /etc/nginx/conf.d/http.conf
fi

if [ ! -L /etc/nginx/conf.d/server.conf ]; then
    echo "Linking /config/nginx/server.conf to /etc/nginx/conf.d/"
    ln -s /config/nginx/server.conf /etc/nginx/conf.d/server.conf
fi

if [ ! -L /etc/nginx/conf.d/location.conf ]; then
    echo "Linking /config/nginx/location.conf to /etc/nginx/conf.d/"
    ln -s /config/nginx/location.conf /etc/nginx/conf.d/location.conf
fi

if [ -e /config/nginx/htpasswd ]; then
    echo "Linking /config/nginx/htpasswd to /etc/nginx/htpasswd"
    ln -s /config/nginx/htpasswd /etc/nginx
fi
